### ISSUE TITLE
docker login containers.mathworks.com may mot work if your account has two factor authentication

### ISSUE THREAD

**Issue by roempertm** [mathworks-ref-arch/matlab-production-server-on-kubernetes#16]
It seems that there is an issue if you try to log into the mathworks docker registry if you have two factor athentication activated for your mathworks account.
I get the following response always and I am sure that my username and password are correct:
Error response from daemon: Get https://containers.mathworks.com/v2/: unauthorized: authentication required

**Comment by esteinerMW** [comment]
Authentication / docker login is no longer required.
Images could be docker pulled directly from containers.mathworks.com.
