### ISSUE TITLE
Configure redis password from secret

### ISSUE THREAD

**Issue by NBonfattiMW** [mathworks-ref-arch/matlab-production-server-on-kubernetes#18]
The bitnami redis chart exposes the redis password as the value of "redis-password" in the "redis" secret. It would be convenient to have an option to get the redis password from the secret so you don't need to pass it into the values.yml

**Comment by esteinerMW** [comment]
This will be addressed in R2023b.

**Comment by esteinerMW** [comment]
Starting from R2023b, the secretName which holds Redis auth key, could be configured in the overrides yaml file.
